# Generated by Django 3.0.8 on 2021-08-14 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import warehouse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/files/category/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('barcode_symbology', models.CharField(blank=True, choices=[('CODE128', 'CODE128'), ('CODE39', 'CODE39'), ('EAN-5', 'EAN-5'), ('EAN-8', 'EAN-8'), ('EAN-13', 'EAN-13'), ('UPC-A', 'UPC-A')], max_length=20)),
                ('rack_location', models.CharField(blank=True, max_length=50)),
                ('SKU', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/files/item/')),
                ('details', models.TextField(blank=True)),
                ('track_quantity', models.BooleanField(default=True)),
                ('track_weight', models.BooleanField(default=False)),
                ('track_variant', models.BooleanField(default=False)),
                ('low_stock_alert_quantity', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ParentCategories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='static/files/transfers/')),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransferAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files/transfer/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/files/warehouse/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option', models.ManyToManyField(to='warehouse.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.BaseUnit')),
            ],
        ),
        migrations.CreateModel(
            name='TransferFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=warehouse.models.attachment_location)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Transfer')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='warehouse.Warehouse'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='item',
            field=models.ManyToManyField(to='warehouse.MovingItem'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_warehouse', to='warehouse.Warehouse'),
        ),
        migrations.AddField(
            model_name='movingitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Unit'),
        ),
        migrations.AddField(
            model_name='movingitem',
            name='variant',
            field=models.ManyToManyField(to='warehouse.ItemVariant'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Option'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Variant'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.ManyToManyField(blank=True, to='warehouse.Variant'),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, upload_to='static/files/checkouts/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Contact')),
                ('items', models.ManyToManyField(to='warehouse.MovingItem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(max_length=30)),
                ('attachment', models.FileField(blank=True, upload_to='static/files/checkins/')),
                ('details', models.TextField(blank=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Contact')),
                ('items', models.ManyToManyField(to='warehouse.MovingItem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.ParentCategory'),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(max_length=30)),
                ('attachment', models.FileField(blank=True, upload_to='static/files/adjustments/')),
                ('details', models.TextField(blank=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='warehouse.MovingItem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Type')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse')),
            ],
        ),
    ]
