# Generated by Django 3.0.8 on 2021-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
