# Generated by Django 3.0.8 on 2021-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210814_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='weight',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='warehouse.MovingItem'),
        ),
    ]
