# Generated by Django 3.0.8 on 2021-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20210815_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, to='warehouse.Variant'),
        ),
    ]
